---
title: ""
page-layout: full
---



## Interview Transcript 

## What is your name? Where did you go? What are you doing now?

  My name is Madeleine Paguio Dia, and I went to De La Salle University (DLSU) Manila, Philippines. I work for the city of Los Angeles in the information security office, specifically for the information technology agency under the chief security officer. 

## What did your “day in a life” experience look like when you went to college in the Philippines? 

I was an everyday, average student who took public transportation. I lived in a nearby suburb in Manila. For transportation, I would take a tricycle ride to the service road, then I’d go via jeepney to a main transportation hub, and then take another jeepney to a bigger transportation hub, and from there I’d take the light-rail (which was like a Philippine metro system)l to my school’s station. The roads weren’t planned out well; they were small even though there was a dense population of Filipinos. I didn’t have the privilege to have a car or a driver. To make my 8:00am class, I would have to leave at 5:30am from my house. Sometimes I would miss the first class due to driver strikes or other situations. As for school itself, my university was on a trimester system. The college made sure that students were only in school for half a day, so either they had all morning classes or all afternoon classes. Since I took computer science, sometimes I’d stay for labs or group projects. 

## What did you study in the Philippines? What are some subjects you focused on? 

I studied computer science and specialized in software technology. During my first-year, I would take the basic computer science classes, then I would choose my specialization after. Currently, they split the major into three categories: computer engineering, computer science, and computer information systems. Back then, it was only one major. Some core subjects I focused on were computer programming, data-based design, neural networks (AI), elective in usability, computer interaction, graphic design, and computer puppetry/animation. 

## Was there any type of academic counseling/advising in the Philippines? If so, what did that look like? If not, how did you navigate your academics?

The student cohort was grouped into sections, and each class was given a section advisor. During the first year, some students didn’t know much about specializations, so they consulted their professors about these things. I knew that I wanted to get into software technology because I liked the front-end of computer programming, so I didn’t really utilize that resource. There was also a dean that students could go to. Overall, we didn’t navigate academics because everything was pre-selected by the college. Since the university tried to have students take classes for only half a day, each class would switch from the morning to the afternoon between each trimester. This encouraged students to not drop out or fail, or else they would have to stay for longer than half a day. I wish that there was more flexibility with this though because sometimes the professors would not be good, but I didn’t want to redo the class the following trimester since I would have to stay there longer. Some students even flunked out due to their mixed schedules. 

## What are some main similarities/differences between the education in the Philippines and the education in the U.S.?

I didn’t experience education in the U.S., but one of the main differences that I observed was the number of classes offered. In the U.S., there were a lot more classes to take. I didn’t have a lot of time in the Philippines to take classes outside my major. In the U.S., some students can take classes on a whim without worrying about finishing their major. I also didn’t have time for extracurriculars due to the school’s rigor. During my PE class, I would play ping pong and even went against my professor. He asked me to join the ping pong team, but I told him that I didn’t have the time for it. When I said I was a computer science major, he immediately understood. \n 

There was also a difference in resources. At the time, the internet was hard to access and I had to manually download images for them to show up. My school used the “Vax System”. There was also more respect towards authorities and professors; we’d often call them sir or ma’am. When students misbehaved, sometimes the professor would put down his chalk and say, “If you’re going to waste your parents’money, it’s up to you”. There was also no housing at my university because of the lack of money and resources. Professors would also announce grades in front of the school. They would say who got a 3.0 GPA, 3.5 GPA, or a 4.0 GPA. 

## What are some aspects of the Philippine education system that seem influenced by the U.S. education system?  

In high school, the system was heavily influenced by the U.S. I went to high school in the province, and I had elementary from first to sixth grade, and then 7th grade was high school. I started college at 16 years old. However, now the Philippines is starting the K-12 system, inspired by that in the United States. The more affluent specific areas are, the more they follow the U.S. structure. So, in the more rural, provincial areas, there was less U.S. influence. 

## Were there opportunities for career development for Filipino students in the Philippines? 

The opportunities for career development were really lacking. Maybe the trade schools would have internships. At La Salle, they had companies for students to intern at. Since they were a more wealthy institution, they had better connections. I got an internship at the United Coconut Planter’s Bank (UCPD). For the top schools, they wanted to maintain a standard for their graduates. They would train us to develop resumes, dress professionally, and do mock interviews. They motivated us to participate in these because we’d level up with our own professional presentation. The quality of resumes was so good that companies could identify a “La Salle” resume. 
 
## Were the classes mainly taught in English, Tagalog, or another Filipino language? What classes were taught in English? In Tagalog? 

All classes were taught in English except for the Tagalog language classes. I was put with other kids from other countries where Tagalog wasn’t the first language. I could speak it fluently, but I couldn’t write well. Taglish was only taught in the province. Despite the language of instruction being English, the government decided that all textbooks in high school would be in Tagalog. Even subjects like accounting and economics were in Tagalog. It was difficult because I had a hard time understanding. 

## What was it like to go from studying in the U.S. to studying in the Philippines?

I moved to the Philippines in 7th grade, and I started my second year of high school in the Philippines. There was a huge language/cultural barrier. Some students would make gestures, but I wouldn’t understand them. There was a lot of jealousy and “chismis” (Filipino gossip). I was still a straight A student though, and I had goals and plans. The quality of education in the Philippines was not good compared to that of the U.S.. Facilities were terrible, transportation wasn’t good. I moved back to the U.S. 8 years after college. 

## Is there anything else that you would like to add on about your experience? 

Looking back, my experience in the Philippines taught me to be resilient and resourceful. I don’t complain about the traffic here because at least it somewhat moves. The traffic in the Philippines was terrible. I realized that the government can really hold back the development of a country, despite the people being hardworking, resourceful, smart, and adaptable. Most students left the Philippines after graduating school. Some of my peers now live in Canada, Singapore, U.S., etc. A lot of Filipinos left abroad because there aren't a lot of quality job opportunities in the Philippines. I learned to appreciate the luxuries we have here; most countries don’t have the modern amenities. \n

On another note, there’s no student loans in the Philippines. There’s financial assistance, but the institution was mainly supported through donations. In 1999, 30,000 pesos a month translates to roughly $1,000-$2,000 here, which was considered a large amount there. 
