---
title: ""
page-layout: full
---

<div class="top-title">
  <h1>The A.R.chives</h1>
</div>

<div class="hero-wrapper">
  <h2 class="hero-subtitle">Introduction the A.R.chives</h2>
</div>

<div class="intro-box">

## Introduction - Julia Aceron, Pomona College, 2028 

As an inspiration to this archive of visual documents and interview transcripts, it began at the beginning of this class, ASAM135 Race Empire Filipinx America. From one of the early articles, "The Mis-education of the Filipino" by Vintage Constantino, I was interested in some of the themes about how the United States had distorted cultural history and heavily influenced education in the Philippines. Later on during class, I began to wonder more about my mom's experience of growing up in the Philippines and how her education there shaped her views. \n 

Referring back to the Constantino article, some highlighted themes that I was interested in were how education centered around the colonial mentality, economic dependence, and how English was the main language of instruction. During my interview with my mom, the questions I asked mainly dealt with her experience with her school's resources (or the lack thereof) and her views on American influence on education in the Philippines. \n

Historically, the colonization of the Philippines by the United States paved the way for their heavy influence on education. According to Rick Baldoz' book, *Third Asiatic Invasion*, the *"Americanization"* program was executed for the purpose of spreading westernized values to the Philippines. Political and economic systems in the Philippines were parallel to that of the United States, which also paved their way to the educational bureaucracy in the Philippines. \n 

Towards a more personal experience, Carlos Bulosan's book, *On Becoming Filipino*, highlighted the struggles of Filipinos when it came to achieving citizenship. One of the main pathways to citizenship was education. From one of his short stories, he illustrated the goals of his cousin, Consorcio, which were to get a good education and become an American citizen. While this particular story focused on getting an education in the United States, I was interested in Consorcio's trajectory towards his dream, and how American education affected his journey. Throughout the story, Consorcio invested in academic books and was motivated to pursue education. However, as time went on, he slowly realized that despite him going to school, learning English, and adapting to American values, he couldn't become a citizen. Eventually, as American policies changed, he got his citizenship status, but lost his Filipino culture and roots along the way. \n

As a result of reading about American education and how the Philippine education system was impacted by American imperialism, I wanted to learn more about my family and their personal experiences in post-secondary education in the Philippines. After interviewing with my mom, I realized that these themes were heavily aligned with her experience. For instance, the economics classes that my mom took in the Philippines were mainly in English. The classes that were in Tagalog were only the Tagalog-based classes, but there were significantly more classes that were taught in English. Another thing to note is that some classes were taught in "Taglish", which is a mixture between Tagalog and English. When I interviewed my tita, she emphasized that her classes were taught ONLY in English. Despite both my mom and tita going to school in the Philippines, it was interesting to see how the level of affluence in different areas influenced the way education was taught. \n 

After conducting these interviews with my mom and tita, I believe that the education in the Philippines is overall heavily influenced by the U.S. system, especially through the classes that are being offered and the language of instruction. A particular part of this process that was interesting for me to find out was how U.S. influence was considered a "privilege", since lower socioeconomic areas in the Philippines were less "Americanized". My mom mentioned how her school had limited resources and career development, and Tagalog was still somewhat implemented in her school. On the other hand, my tita mentioned how her school had strong connections to companies, and English was the only language of instruction with the exception of some Tagalog-only literature classes. These trends definitely parallel the goals of the U.S., where they want higher institutions in the Philippines to focus more on westernized education. \n 

Through this website, I have included interview transcripts and provided photo libraries for both my mom and tita. Their photo archives highlight their experience with education in the Philippines, and I hope to emphasize the  influence of their education on their current everyday lives. 



## Introduction - Alessi Rodil, Pomona College, 2028

A lot of the materials in this class influenced my inclination to piece together a narrative of my family’s migration history and to better understand how Filipinx migrant labor played a significant role in their journey. One of the articles, “Migrant Heroes: Nationalism, Citizenship, and the Politics of Filipino Migrant Labor” by Robyn Rodriguez, discusses how migrant workers are crucial to the Philippine economy and national identity, often framed as icons of the nation’s export-oriented development. Through remittances, they generate foreign exchange that sustains both their families and the Philippine economy. These ideas resonated deeply with my own family’s history, both in the past and present, such as the remittances that supported family members in the Philippines through my grandparents’ work in Saudi Arabia, and the remittances that my grandmother continues to send to her family in the Philippines today. I also recognized the systemic factors and emotional effects of migrant labor on family members left behind through the film Anak, directed by Rory Quintos, which reflected experiences my dad often recalls. \n

In addition to overseas Filipinx labor, I was also interested in exploring the factors that led to my family’s long-term migration to the United States. In The Third Asiatic Invasion, Rick Baldoz shows that U.S. colonialism shaped Filipinos’ idealization of America by training them to see the United States as both benevolent and attainable. He explains that American colonial education in the Philippines promoted U.S. democratic ideals while positioning Filipinos as future participants in American modernity, producing what he describes as a population that was “educated for empire.” I wanted to explore how these U.S.-influenced ideals and educational structures continue to shape the decisions of Filipinos today. \n

Through these oral interviews and photo archive, I was able to piece together my grandmother’s early life in the Philippines and the factors that led her family to migrate to Saudi Arabia, return to the Philippines, and eventually come to the United States, all while my father grew up caught between these places.
I want to examine how Filipinx overseas workers, especially my grandparents, experience migration as a multi-stage process: beginning with temporary labor migration in the Middle East and eventually transitioning into long-term or family-based migration to the United States. My interview with my dad explores his perspective on transnationalism, multi-stage migration, and the ways these movements shaped his own trajectory of immigration and identity. His story provides an intergenerational lens on how migration has shaped our family, revealing how broader systems of labor, empire, and colonialism intersect with personal histories. \n 

Through this project, I hope to piece together a narrative of my family’s immigration, one that reflects the layered realities of Filipinx people in the diaspora.



